### PR TITLE
Plone 5.1.x support

### PR DESCRIPTION
**Pull request by maethu**
Add support for Plone 5.1.

Changes needed:
- There is no `<base>`-tag anymore.
- lxml has changed regarding file uploads.
- Factories menu markup has changed.
- Folder-Contents was reimplemented with JavaScript, the page object is therefore obsolete.
- The user menu markup has changed.
- The status messages markup has changed.
- Various minor changes.
- New autocomplete widget.

### CODE REVIEW

**Comment by phgross** [comment]
@jone :shipit: ?

**Comment by jone** [comment]
@phgross do you need that soon? Because we will need to rebase everything 🤔

**Comment by phgross** [comment]
@jone There's no hurry. I just saw that it would be ready to merge and still open.

**Comment by jone** [comment]
Ah ok. It's not really ready, because we need to rebase onto the driver refactoring and the new traversal driver. Some changes need to be made.

**Pull request closed without merging**
